Feature/consolidate parsers
raphaeldussin/om4labs pull request #39
Opened 2020-10-27 12:13 UTC by jkrasting

- standalone PR for a common CLI parser.

2020-10-27 21:03 UTC, raphaeldussin requested changes
minor changes and good to go

2020-10-27 21:03 UTC, raphaeldussin commented on om4labs/om4parser.py
> +            "--configuration",
--config? a bit shorter

2020-10-28 11:29 UTC, jkrasting commented on om4labs/om4parser.py
> +    -m, --model:        str; model configuration (e.g. OM4p25, OM4p5, OM4p125)
Addressed in 480f9bf

2020-10-28 11:30 UTC, jkrasting commented on om4labs/om4parser.py
> +            "--configuration",
Addressed in 480f9bf

2020-10-28 14:34 UTC, merged