Generic functions to read horizontal grid and topography
raphaeldussin/om4labs pull request #54
Opened 2020-11-12 21:58 UTC by jkrasting

Centralizes intake catalog logic
Default WOA horizontal grid is returned when no options are passed
Enforces order for obtaining grid & topo data based on parser options
Allows for the basin mask to be computed on the requested grid (t,u,v,q)
Grid returned either as xarray dataset (default) or tuple of numpy arrays

Closes #40

2020-11-12 22:18 UTC, raphaeldussin requested changes

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +        verbose = dictArgs["verbose"]
verbose is already a kwarg in function

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +        basin_file = dictArgs["basin"]
```python
basin_file = dictArgs["basin"] if basin in dictArgs else None
```

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +    elif dictArgs["hgrid"] is not None:
```python
if "hgrid" in dictArgs:
```

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +        if verbose is True:
```python
if verbose:
```

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +    elif dictArgs["static"] is not None:
```python
if "static" in dictArgs:
```

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +        if verbose is True:
```python
if verbose:
```

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +    elif dictArgs["gridspec"] is not None:
same remarks

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +        geolat = subsample_supergrid(ds, "y", point_type)  # , outputgrid='symetric')
you could write a small function `grid_from_supergrid` to avoid repeting the same 3 lines

2020-11-12 22:18 UTC, raphaeldussin commented on om4labs/om4common.py
> +def read_topography(dictArgs, verbose=False):
if dictArgs can be None, let's make it a kwarg

2020-11-12 23:06 UTC, jkrasting commented
Thanks @raphaeldussin.  I'll fix these up and add in docstrings.

2020-11-13 21:53 UTC, raphaeldussin approved these changes

2020-11-14 01:27 UTC, merged