Decode bounds in np.timedelta64 format
raphaeldussin/om4labs pull request #63
Opened 2021-01-08 21:44 UTC by jkrasting

- Xarray decodes bounds times relative to the epoch and
  returns a numpy timedelta object in some instances
  instead of a cftime datetime object. Manual decoding
  and shifting may be necessary

2021-01-21 23:24 UTC, raphaeldussin requested changes

2021-01-21 23:24 UTC, raphaeldussin commented on om4labs/om4common.py
> +            offset = base_time - np.datetime64("1970-01-01T00:00:00Z")
can we make the reference date a kwarg?

2021-01-22 16:31 UTC, jkrasting commented on om4labs/om4common.py
> +            offset = base_time - np.datetime64("1970-01-01T00:00:00Z")
Sure

2021-01-22 16:39 UTC, raphaeldussin approved these changes

2021-01-22 16:39 UTC, merged