Implement xoverturning for MOC diagnostic
raphaeldussin/om4labs pull request #69
Opened 2021-03-19 17:43 UTC by jkrasting

**Updates:**
- Uses external `xoverturning` package
- Separate plotting module with routines for z-level and rho2
- Dropped support for pre-computed `msftyyz` field
- Extensive documentation

**Unresolved Issues:**
- The sigma2 plots invoke the `VerticalSplitScale` transform to expand the higher density region, but the y-ticks cannot be altered despite a call to `ax.set_yticks()`
- The MOC plots from `xoverturning`(middle,right) are very noisy compared to the original method (left)

![image](https://user-images.githubusercontent.com/6594675/111821080-a3e53680-88b8-11eb-8c1b-4a6973cefb4d.png)

2021-03-25 03:13 UTC, raphaeldussin commented
please try the `masking` branch from `xoverturning`, using:

```python
from xoverturning.moc import calcmoc
moc = calcmoc(ds, dsgrid, mask_output=True, basin="atl-arc")
```

this should make it much easier since `xoverturning` can do the merging of grid and transports and mask the end result

2021-03-29 19:44 UTC, jkrasting commented
Noise is now fixed through update to `xoverturning`

![image](https://user-images.githubusercontent.com/6594675/112891034-a1978f00-90a5-11eb-80f5-ae3bfff1e598.png)

2021-03-31 18:00 UTC, raphaeldussin requested changes

2021-03-31 18:00 UTC, raphaeldussin commented on om4labs/om4common.py
> +def is_symmetric(dset, center="yh", corner="yq"):
maybe use the similar function defined in xoverturning?

2021-04-01 17:02 UTC, jkrasting commented on om4labs/diags/moc/moc.py
> +    # get topography info
Yes, in the case that `ocean_hgrid.nc` is provided instead of `ocean_static.nc`.  Regardless, it doesn't belong here.  I'll move it to om4common.

2021-04-01 17:03 UTC, jkrasting commented on om4labs/diags/moc/moc.py
> +        otsfn = otsfn.mean(dim="time")
Good idea.  Will add ...

2021-04-01 22:34 UTC, raphaeldussin commented on om4labs/diags/moc/moc.py
> +    fig = plot(dset, otsfn, dictArgs["label"],)
still there

2021-04-01 23:33 UTC, jkrasting commented on om4labs/om4common.py
> +            | (basin_code == 4)
Yes

2021-04-01 23:37 UTC, jkrasting commented on om4labs/diags/moc/moc.py
> +    fig = plot(dset, otsfn, dictArgs["label"],)
You're right.  Fixed in 2ffa932

2021-04-01 23:44 UTC, raphaeldussin approved these changes

2021-04-01 23:45 UTC, merged