Thermocline analysis
raphaeldussin/om4labs pull request #89
Opened 2021-10-26 16:27 UTC by jkrasting

2021-11-18 16:03 UTC, jkrasting commented on om4labs/diags/stratification/stratification.py
> +    # standardize longitude to go from 0 to 360.
We can create a common function that will standardize the lon range by searching for the minimum value and the roll the index to make the minimum value the start of the array.

2021-11-18 23:48 UTC, jkrasting commented on om4labs/diags/stratification/stratification.py
> +    # standardize longitude to go from 0 to 360.
#90 should address this

2021-11-19 14:25 UTC, jkrasting commented on om4labs/diags/stratification/stratification.py
> +    # standardize longitude to go from 0 to 360.
And see a3efb5a

2021-11-23 13:30 UTC, jkrasting commented
@raphaeldussin - this PR depends on #90.  Any other comments?

2021-11-23 15:04 UTC, raphaeldussin commented
#90 is merged, can you rebase?

2021-11-23 15:38 UTC, jkrasting commented
@raphaeldussin - rebased against your master.

2022-01-26 15:46 UTC, raphaeldussin commented
@jkrasting I have merged a PR with a notebook to create the ARGO T/S clim data. When you have a chance, can you test the file works and we should put the file into the common archive so we need to change paths in the intake catalogs

2022-01-26 19:38 UTC, jkrasting commented
@raphaeldussin - this works with the data notebook you supplied.

2022-03-13 22:43 UTC, raphaeldussin requested changes

2022-03-13 22:43 UTC, raphaeldussin commented on om4labs/catalogs/obs_catalog_gfdl.yml
> +      urlpath: ['/net2/bgr/Data/ARGO/RG_Clim/Updated/RG_ArgoClim_Temp_Extended_200401-202010.nc', '/net2/bgr/Data/ARGO/RG_Clim/Updated/RG_ArgoClim_Psal_Extended_200401-202010.nc']
point to merged T/S file here: `/archive/Raphael.Dussin/datasets/Roemmich_Gilson_ARGO_TS_Clim`

2022-03-13 22:43 UTC, raphaeldussin commented on om4labs/catalogs/obs_catalog_gfdl.yml
> +      urlpath: '/net2/bgr/Data/ARGO/RG_Clim/Updated/RG_ArgoClim_Temp_Extended_200401-202010.nc'
same

2022-03-13 22:43 UTC, raphaeldussin commented on om4labs/catalogs/obs_catalog_gfdl.yml
> +      urlpath: '/net2/bgr/Data/ARGO/RG_Clim/Updated/RG_ArgoClim_Psal_Extended_200401-202010.nc'
same

2022-03-13 22:43 UTC, raphaeldussin commented on om4labs/catalogs/obs_catalog_testing.yml
> +      urlpath: ['test_data/obs/RG_ArgoClim_Temp_Extended_200401-202010.nc', 'test_data/obs/RG_ArgoClim_Psal_Extended_200401-202010.nc']
probably needs a new copy

2022-03-13 22:43 UTC, raphaeldussin commented on om4labs/catalogs/obs_catalog_testing.yml
> +      urlpath: 'test_data/obs/RG_ArgoClim_Temp_Extended_200401-202010.nc'
merged T and S

2022-03-13 22:43 UTC, raphaeldussin commented on om4labs/catalogs/obs_catalog_testing.yml
> +      urlpath: 'test_data/obs/RG_ArgoClim_Psal_Extended_200401-202010.nc'
same

2022-03-13 22:43 UTC, raphaeldussin commented on om4labs/diags/stratification/stratification.py
> +    tempvar = "thetao"
move into kwargs for read?

2022-03-14 17:39 UTC, jkrasting commented
@raphaeldussin - can you break out the mean fields (`ARGO_TEMPERATURE_MEAN` and `ARGO_SALINITY_MEAN`) into their own file?  The complete file at 5 GB is a bit too much for a speedy analysis on Dora and for the testing tarball.

2022-03-15 02:30 UTC, raphaeldussin commented
fair! I have built annual and monthly clim for potential temperature and salinity in the same directory

2022-03-16 12:19 UTC, merged