Stress curl
raphaeldussin/om4labs pull request #92
Opened 2021-12-01 17:14 UTC by StephenGriffies

First draft of stress_curl diagnostic for om4labs.  Will need further edits but ready for input from @raphaeldussin .

2021-12-09 21:48 UTC, raphaeldussin requested changes
@StephenGriffies @jkrasting we probably need to discuss some strategic choices here for the comparison. Otherwise it looks great!

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/example_stress_curl.ipynb
> + "cells": [
I don't think we need to add the example notebook.
They are too heavy because of the plots,...

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/example_stress_curl.ipynb
> + "cells": [
you can make a backup somewhere and `git rm example_stress_curl.ipynb`

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +    parser.add_argument(
I have a dilemma on what the best strategy for comparison is here. By doing the comparison inside om4labs, we need to duplicate read and calculate code (ref and model) before we can pass to xcompare and we always need a reference dataset. I think we could write the diag for one dataset and then I would build a generic wrapper to call 2 instances of the diag's read and calculate and pass the result to xcompare.

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +    taux = ds[varx]
we can shorten with:
`taux = ds[varx].mean(dim="time")`

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +def calc_curl_stress(
with one ds, `calc_curl_stress` would become `calculate`

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +    rho0 = 1035.0
add to oprional args?

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +    stress_curl = stress_curl.where(ds_static["wet_c"] == 1)
"wet_c", "geolon_c",... should be stored as default to kwargs in case someone has different naming convention

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +    fig = xcompare.plot_three_panel(results, "stress_curl", cmap=cmocean.cm.delta,
see earlier remark

2021-12-09 21:48 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +def plot_old(
"this is the way" :+1:

2022-01-25 22:59 UTC, raphaeldussin approved these changes
approved pending merge of my PR to this PR

2022-01-25 22:59 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +    parser.add_argument(
after discussing with @jkrasting we still think the compare on top of om4labs is a good idea but will need some more work and I don't want to hold back this PR

2022-01-25 22:59 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +    rho0 = 1035.0
will be fixed with merge by PR to your branch

2022-01-25 22:59 UTC, raphaeldussin commented on om4labs/diags/stress_curl/stress_curl.py
> +def plot_old(
please keep function for future use

2022-01-25 23:07 UTC, StephenGriffies commented
Thanks for this @raphaeldussin . 

I am unsure if there is an action for me here, of if this approval means that it is now in your hands and will be brought into OM4labs.  Please advise.

2022-01-25 23:12 UTC, raphaeldussin commented
I've made a PR to your branch with some fixes, you need to merge it first and I'll then do the final merge

2022-01-27 16:04 UTC, raphaeldussin commented
woot woot!! thanks @StephenGriffies and @jkrasting for this very nice diagnostic

2022-01-27 16:04 UTC, merged